# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Coworking in Cameroon
email: contact@coworkingcameroon.space
description: > # this means to ignore newlines until "baseurl:"
  Find coworking spaces in Douala, Yaounde, kribi, Maroua and Buea
baseurl: "/coworking" # the subpath of your site, e.g. /blog
spaces_img_url: "/coworking/images/spaces/"
url: "http://zatech.github.io" # the base hostname & protocol for your site
twitter_username: offerzen
facebook_page: offerzen
github_username: coworkingcameroon

# Build settings
markdown: kramdown
